version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
    build:
        working_directory: ~/app
        environment:
            NODE_ENV: development
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Update NPM
                command: 'sudo npm install -g npm@latest'
            - run:
                name: Installing jest
                command: 'sudo npm install -g jest'
            - run:
                name: Installing packages
                command: npm install
            - run:
                name: report coverage
                command: npm run coverage
            - codecov/upload:
                file: './coverage/coverage-final.json'
