version: 2

jobs:
    build:
        working_directory: ~/app
        environment:
            NODE_ENV: development
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Update NPM
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Installing packages
                command: npm install
            - run:
                name: Install mocha-junit-reporter
                command: npm install mocha-junit-reporter
            - save-cache:
                paths:
                    - ./node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: mkdir reports
            - run:
                name: npm test
                command: ./node_modules/.bin/nyc ./node_modules/.bin/mocha --recursive --timeout=10000 --exit --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml
            - run:
                name: report coverage
                command: npm run coverage
            - store_test_results:
                path: reports
            - store_artifacts:
                path: ./reports/mocha/test-results.xml
