version: 2

jobs:
    build:
        working_directory: ~/app
        environment:
            NODE_ENV: development
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Update NPM
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Installing packages
                command: npm install
            - save-cache:
                paths:
                    - ./node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: mkdir reports
            - run:
                name: npm test
                command: npm test
            - run:
                name: report coverage
                command: npm run coverage
            - store_artifacts:
                path: coverage
                prefix: coverage
