version: 2

jobs:
    build:
        working_directory: ~/app
        environment:
            NODE_ENV: development
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run:
                name: Update NPM
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run:
                name: Installing packages
                command: npm install
            - run:
                name: Install mocha-junit-reporter
                command: npm install mocha-junit-reporter
            - save-cache:
                paths:
                    - ./node_modules
                keys: v1-dependencies-{{ checksum "package.json" }}
            - run: mkdir reports
            - run:
                name: npm test
                command: npm test
            - run:
                name: code coverage
                command: './node_modules/.bin/nyc report --reporter=text-lcov'
            - store_artifacts:
                path: test-results.xml
                prefix: tests
            - store_artifacts:
                path: coverage
                prefix: coverage
            - store_test_results:
                path: test-results.xml
